version: "3.8"
services:
  cloudprober:
    image: cloudprober/cloudprober:v0.11.1
    environment:
      HTTP_PROXY: http://proxy:8888
      HTTPS_PROXY: http://proxy:8888
    volumes:
      - "./cloudprober/cloudprober.cfg:/etc/cloudprober.cfg:ro"
  proxy:
    image: vimagick/tinyproxy:latest
  nginx:
    image: nginx:1.19.7
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./nginx/key.pem:/etc/nginx/key.pem:ro"
      - "./nginx/cert.pem:/etc/nginx/cert.pem:ro"
  prometheus:
    image: prom/prometheus:v2.25.0
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
  grafana:
    image: grafana/grafana:7.4.3
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
    ports:
      - "3000:3000"

